### ISSUE TITLE
我来玩玩

### ISSUE THREAD

**Issue by yasuoman** [xx790008409/Code_Line_Corr#1]
cacl_rank.py里面的find_closest_num()函数：

    if str(target + min_diff_val) in real_line_data:
        return str(target + min_diff_val)
    if str(target - min_diff_val) in real_line_data:
        return str(target - min_diff_val)

距离一样的，如365距离364,366距离一样，但是返回的就是366了，但是结果还是会受影响，随缘了，阿弥陀佛！

**Comment by xie-huan** [comment]
刚刚处理了你说的这种情况，方法如下：将两个值作为列表返回，处理列表元素即可

**Comment by yasuoman** [comment]
> 刚刚处理了你说的这种情况，方法如下：将两个值作为列表返回，处理列表元素即可

**Comment by yasuoman** [comment]
么么哒
