### ISSUE TITLE
关于calc_rank.py 里面的find_closest_num函数

### ISSUE THREAD

**Issue by yasuoman** [xx790008409/Code_Line_Corr#3]
传入find_closest_num（）函数的real_line_data，这个列表里面的值的类型是str,但是你判断在不在real_line_data里面的时候前面的类型是int 类型，我尝试了一下，
`lst=[4,'45']
p=45
print(int(p) in lst)`

输出为false。
但是我在本地数据中没调试，不知道哪个版本会执行find_closest_num（）函数。

**Comment by xie-huan** [comment]
现在代码库中数据已进行标准化，代码行为int，系数值为float。

**Comment by xie-huan** [comment]
详情请见process_content.py中process_corr_data函数中，已将代码行标准化为int型。
